Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Style/MultilineTernaryOperator:
  Enabled: false

Lint/SuppressedException:
  Enabled: false
